name: Build image

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  # Run daily at a specific time (e.g., 04:00 AM UTC)
  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: read

env:
  FINAL_IMAGE: quay.io/coreos-devel/fedora-coreos-nvidia

jobs:
  podman_build:
    name: Podman Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        STREAM: [42]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build the builder image
        run: |
          source build-args.conf
          podman build --build-arg-file build-args.conf --build-arg STREAM="${{ matrix.STREAM }}" -f Containerfile.builder -t $BUILDER_IMAGE

      - name: Build FCOS image with NVIDIA bits
        run: |
          NVIDIA_DRIVER_VERSION=$(grep -e "^DRIVER_VERSION" build-args.conf | cut -d= -f2)
          FINAL_IMAGE_TAG="${{ matrix.STREAM }}-${NVIDIA_DRIVER_VERSION}"
          podman build --build-arg-file build-args.conf --build-arg STREAM="${{ matrix.STREAM }}" -f Containerfile -t $FINAL_IMAGE:$FINAL_IMAGE_TAG

      - name: Sanity-check
        run: |
          NVIDIA_DRIVER_VERSION=$(grep -e "^DRIVER_VERSION" build-args.conf | cut -d= -f2)
          FINAL_IMAGE_TAG="${{ matrix.STREAM }}-${NVIDIA_DRIVER_VERSION}"
          podman run --rm $FINAL_IMAGE:$FINAL_IMAGE_TAG echo hello
